flask_frontend/blueprints/games/forms.py
# -*- coding: utf-8 -*-
# author: Jakub Skałecki (jakub.skalecki@gmail.com)
import wtforms
from flask_babel import gettext
from wtforms.validators import Length

from flask_frontend.common.api_helper import ApiForm

nickname_field = wtforms.StringField(gettext('Nickname'))


class GameJoinForm(ApiForm):

    nickname = nickname_field

    def __init__(self, api, token, game_id, user_id, *args, **kwargs):
        """
        :type game_ownership_id: int
        :return:
        """
        super(GameJoinForm, self).__init__(api, *args, **kwargs)
        self.token = token
        self.game_id = game_id
        self.user_id = user_id

    def _make_request(self):
        return self._api.game_ownerships.create(
            token=self.token, user_id=self.user_id, game_id=self.game_id, nickname=self.nickname.data)


class GameUpdateForm(ApiForm):

    nickname = nickname_field

    def __init__(self, api, token, game_ownership_id, *args, **kwargs):
        super(GameUpdateForm, self).__init__(api, *args, **kwargs)
        self.game_ownership_id = game_ownership_id
        self.token = token

    def _make_request(self):
        return self._api.game_ownerships.update(
            token=self.token, game_ownership_id=self.game_ownership_id, nickname=self.nickname.data)

flask_frontend/blueprints/games/__init__.py
# -*- coding: utf-8 -*-
# author: Jakub Skałecki (jakub.skalecki@gmail.com)

import flask

from .views import create_routes, init_blueprint


def create_blueprint(env):
    games_blueprint = flask.Blueprint('games', __name__, template_folder='templates')
    init_blueprint(games_blueprint, env)
    create_routes().register(games_blueprint, env)
    return games_blueprint

flask_frontend/blueprints/games/views.py
# -*- coding: utf-8 -*-
# author: Jakub Skałecki (jakub.skalecki@gmail.com)

import flask
from flask_babel import gettext
import flask_login

from api.models import Game
from common.utils import hash_by
from flask_frontend.common.view_helpers.contexts import IndexView
from flask_frontend.common.view_helpers.response_processors import TemplateRenderer, TemplateView, template_view
from flask_frontend.common.view_helpers.routes import UrlRoute, UrlRoutes
from flask_frontend.blueprints.games.forms import GameUpdateForm, GameJoinForm
from flask_frontend.common.flash import Flash
from flask_frontend.common.api_helper import get_or_404, get_or_none


def create_routes():
    return UrlRoutes([
        UrlRoute('/', IndexView(Game, TemplateRenderer('games.html'))),
        UrlRoute('/<int:game_id>/', TemplateView('game.html', create_edit_context), endpoint='game_view'),
        UrlRoute('/<int:game_id>/join', join, methods=['POST']),
        UrlRoute('/<int:game_id>/leave', leave, methods=['POST'])
    ])


def init_blueprint(blueprint, env):
    @blueprint.before_app_request
    def before_request():
        if 'static' not in flask.request.url:
            flask.g.games = get_or_none(env.api.games.get) or []


def create_edit_context(env, game_id):
    user = flask_login.current_user
    game = get_or_404(env.api.games.get_single, game_id=game_id)
    game_ownership = None
    form = None
    if user.is_authenticated():
        game_ownerships_by_game_id = hash_by(lambda go: go.game.id, user.game_ownerships)
        game_ownership = game_ownerships_by_game_id.get(game_id)
        if game_ownership:
            form = GameUpdateForm(env.api, user.token, game_ownership.id)
        else:
            form = GameJoinForm(env.api, user.token, game_id, user.id)
    return dict(game_ownership=game_ownership, form=form, game=game)


@template_view('game.html', create_edit_context)
@flask_login.login_required
def join(form):
    if form.validate_on_submit():
        Flash.success(gettext('Successfully updated!'))
        return dict(game_ownership=form.result)


@template_view('game.html', create_edit_context)
@flask_login.login_required
def leave(env, game_ownership):
    if game_ownership:
        delete = get_or_none(
            env.api.game_ownerships.delete, token=flask_login.current_user.token, game_ownership_id=game_ownership.id)
        if delete and delete.success:
            Flash.success("Successfully leaved game")
    else:
        Flash.error("Unable to leave game")

flask_frontend/blueprints/games/templates/game.html
{% extends 'main.html' %}

{% block content %}
<div class="profile game col-md-9">
	<div class="row">
		<div class="menu">
			<div class="logo">
				<img class="avatar" src="{{ url_for('static', filename='images/lol-icon.png') }}" alt="" />
			</div>
			<ul>
				<li><a href="#" class="active">{{ gettext('Info') }}</a></li>
				<li><a href="#">{{ gettext('Leagues and tournaments') }}</a></li>
				<li><a href="#">{{ gettext('Media') }}</a></li>
			</ul>
		</div>
		<div class="content">
			<h1 class="name">
				<span>{{ game.name }}</span>
			</h1>

			<h3>{{ gettext('Game description') }}</h3>
			<p>Butcher locavore vegan chillwave fingerstache. Post-ironic meditation artisan Wes Anderson polaroid. Fap tofu High Life seitan raw denim. Readymade 90's keytar, viral kale chips gastropub pork belly Portland hoodie paleo. Slow-carb bicycle rights tilde, bespoke leggings kitsch health goth meditation brunch trust fund Vice cardigan polaroid whatever Neutra. Meh PBR&B before they sold out art party polaroid quinoa, Wes Anderson sartorial ennui skateboard Schlitz. Direct trade before they sold out biodiesel flannel, asymmetrical Echo Park swag salvia.</p>

			{% if current_user.is_authenticated() %}
                {% if game_ownership %}
                  <form method="post" action="{{ url_for('games.leave', game_id=game.id) }}">
                    <button>(Leave)</button>
                  </form>
                {% endif %}
				<h3>{{ gettext('Join game' if not game_ownership else 'Update nickname') }}</h3>

				{% from 'macros.html' import render_form %}
				{{ render_form(form, url_for('games.join', game_id=game.id), action_text=gettext('Save')) }}

			{% endif %}
			<h3>{{ gettext('Rules') }}</h3>
			<div role="tabpanel" class="row rules">

			  <!-- Nav tabs -->
			  <ul class="nav nav-stacked col-sm-4" role="tablist">
                {% for rule in game.rules %}
                  <li role="presentation" {{ 'class=active' if loop.first else '' }}>
                    <a href="#rules-{{ loop.index }}" aria-controls="lol-rules-{{ loop.index }}" role="tab" data-toggle="tab">{{ rule.name }}</a>
                  </li>
                {% endfor %}
			  </ul>

			  <!-- Tab panes -->
			  <div class="tab-content col-sm-8">
                  {% for rule in game.rules %}
                  <div role="tabpanel" class="tab-pane {{ 'active' if loop.first else '' }}" id="rules-{{ loop.index }}">
                      {% for entry in rule.entries %}
                        <h4>{{ entry.key }}</h4>
                        <p>{{ entry.value }}</p>
                      {% endfor %}
                  </div>
                  {% endfor %}
                </div>

			</div>
			
		</div>
	</div>
</div>


{% endblock content %}

flask_frontend/blueprints/games/templates/games.html
{% extends 'main.html' %}

{% block content %}
<div class="games col-md-9">
	<h1>{{ gettext("Games") }}</h1>
	<div class="row">
	{% for game in g.games %}
		<div class="col-sm-6 col-md-4 game">
			<a href="{{ url_for('games.game_view', game_id = game.id) }}" style="background-image: url({{ url_for('static', filename='images/game.jpg') }});">
				<div class="info">
					<h3>{{ game.name }}</h3>
					<div class="row">
						<div class="col-xs-6"><i class="fa fa-calendar"></i> 5</div>
						<div class="col-xs-6"><i class="fa fa-trophy"></i> 7</div>
					</div>
				</div>
			</a>
		</div>
  {%  endfor %}
	</div>
</div>
{% endblock content %}